#!/usr/bin/env node
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const crypto = require('crypto');

const ROOT = '/Users/johnpeng/career_data/code/openbook-baoyi';
const DATA_FILE = path.join(ROOT, 'src/data/interviewDrillData.js');
const OUT_FILE = path.join(ROOT, 'supabase/seeds/20260408_interview_drill_v2_seed.sql');

function esc(str = '') {
  return String(str).replace(/'/g, "''");
}

function loadData() {
  const src = fs.readFileSync(DATA_FILE, 'utf8');
  const wrapped = src
    .replace('export const sharedAnswerLibrary =', 'const sharedAnswerLibrary =')
    .replace('export const interviewCategories =', 'const interviewCategories =') +
    '\nmodule.exports = { interviewCategories, sharedAnswerLibrary };';

  const sandbox = {module: {exports: {}}};
  vm.createContext(sandbox);
  new vm.Script(wrapped, {filename: DATA_FILE}).runInContext(sandbox);
  return sandbox.module.exports;
}

function walkNodes(nodes, parentPath, cb) {
  nodes.forEach((node, idx) => {
    const pathArr = [...parentPath, idx + 1];
    cb(node, pathArr);
    walkNodes(node.followUps || [], pathArr, cb);
  });
}

function main() {
  const {interviewCategories, sharedAnswerLibrary} = loadData();

  const categories = [];
  const answersBySlug = new Map();
  const questions = [];
  const chainNodes = [];

  // preload shared answers
  Object.entries(sharedAnswerLibrary || {}).forEach(([slug, v]) => {
    answersBySlug.set(`shared_${slug}`, {
      id: crypto.randomUUID(),
      slug: `shared_${slug}`,
      oral_text: v.oral || '',
      deep_text: v.deep || v.oral || '',
      is_active: true,
    });
  });

  for (const c of interviewCategories) {
    const categoryId = crypto.randomUUID();
    categories.push({
      id: categoryId,
      slug: c.id,
      label: c.label,
      heat: c.heat || 'A',
      sort_order: 100,
    });

    c.questions.forEach((q, qIdx) => {
      const qSlug = q.id;
      const qId = crypto.randomUUID();
      const a0Slug = q.a0AnswerRef ? `shared_${q.a0AnswerRef}` : `q_${qSlug}_a0`;
      if (!answersBySlug.has(a0Slug)) {
        answersBySlug.set(a0Slug, {
          id: crypto.randomUUID(),
          slug: a0Slug,
          oral_text: q.a0 || '',
          deep_text: q.a0Deep || q.a0 || '',
          is_active: true,
        });
      }

      questions.push({
        id: qId,
        category_id: categoryId,
        slug: qSlug,
        title: q.title,
        q1: q.q1,
        a0_answer_id: answersBySlug.get(a0Slug).id,
        aliases: q.aliases || [],
        sort_order: qIdx + 1,
        is_active: true,
      });

      for (const chainType of ['A', 'B']) {
        const chain = chainType === 'A' ? q.chainA : q.chainB;
        const nodeIdByPath = new Map();

        walkNodes(chain || [], [], (node, pathArr) => {
          const nodePath = pathArr.join('.');
          const parentPath = pathArr.slice(0, -1).join('.');
          const nodeId = crypto.randomUUID();
          nodeIdByPath.set(nodePath, nodeId);

          const answerSlug = node.answerRef
            ? `shared_${node.answerRef}`
            : `q_${qSlug}_${chainType}_${nodePath}_ans`;

          if (!answersBySlug.has(answerSlug)) {
            answersBySlug.set(answerSlug, {
              id: crypto.randomUUID(),
              slug: answerSlug,
              oral_text: node.a || '',
              deep_text: node.deepAnswer || node.a || '',
              is_active: true,
            });
          }

          const depth = pathArr.length;
          let closeReason = node.closeReason || 'NONE';
          if (depth >= 4 && closeReason === 'NONE') {
            closeReason = 'FORCED_CLOSE_AT_DEPTH_4';
          }

          chainNodes.push({
            id: nodeId,
            question_id: qId,
            chain_type: chainType,
            parent_key: parentPath || null,
            prompt: node.q || '',
            answer_id: answersBySlug.get(answerSlug).id,
            depth,
            close_reason: closeReason,
            sort_order: pathArr[pathArr.length - 1],
            _nodePath: nodePath,
            _pathMapRef: nodeIdByPath,
          });
        });

        // resolve parent_id after map built
        chainNodes.forEach((n) => {
          if (n.question_id !== qId || n.chain_type !== chainType) return;
          if (!n.parent_key) {
            n.parent_id = null;
            return;
          }
          n.parent_id = nodeIdByPath.get(n.parent_key) || null;
        });
      }
    });
  }

  const answers = Array.from(answersBySlug.values());

  const lines = [];
  lines.push('-- Auto-generated seed for interview drill v2');
  lines.push('-- Generated by scripts/generate_interview_seed_v2.cjs');
  lines.push('begin;');
  lines.push('delete from public.interview_chain_nodes;');
  lines.push('delete from public.interview_questions;');
  lines.push('delete from public.interview_answers;');
  lines.push('delete from public.interview_categories;');

  lines.push('\n-- categories');
  categories.forEach((c) => {
    lines.push(
      `insert into public.interview_categories (id, slug, label, heat, sort_order, created_at, updated_at) values ('${c.id}', '${esc(c.slug)}', '${esc(c.label)}', '${esc(c.heat)}', ${c.sort_order}, now(), now());`
    );
  });

  lines.push('\n-- answers');
  answers.forEach((a) => {
    lines.push(
      `insert into public.interview_answers (id, slug, oral_text, deep_text, is_active, created_at, updated_at) values ('${a.id}', '${esc(a.slug)}', '${esc(a.oral_text)}', '${esc(a.deep_text)}', ${a.is_active ? 'true' : 'false'}, now(), now());`
    );
  });

  lines.push('\n-- questions');
  questions.forEach((q) => {
    const aliases = `{${(q.aliases || []).map((x) => `"${String(x).replace(/"/g, '\\"')}"`).join(',')}}`;
    lines.push(
      `insert into public.interview_questions (id, category_id, slug, title, q1, a0_answer_id, aliases, sort_order, is_active, created_at, updated_at) values ('${q.id}', '${q.category_id}', '${esc(q.slug)}', '${esc(q.title)}', '${esc(q.q1)}', '${q.a0_answer_id}', '${aliases}', ${q.sort_order}, ${q.is_active ? 'true' : 'false'}, now(), now());`
    );
  });

  lines.push('\n-- chain nodes');
  chainNodes.forEach((n) => {
    lines.push(
      `insert into public.interview_chain_nodes (id, question_id, chain_type, parent_id, prompt, answer_id, depth, close_reason, sort_order, created_at, updated_at) values ('${n.id}', '${n.question_id}', '${n.chain_type}', ${n.parent_id ? `'${n.parent_id}'` : 'null'}, '${esc(n.prompt)}', '${n.answer_id}', ${n.depth}, '${n.close_reason}', ${n.sort_order}, now(), now());`
    );
  });

  lines.push('commit;');

  fs.writeFileSync(OUT_FILE, lines.join('\n') + '\n', 'utf8');
  console.log(`Generated ${OUT_FILE}`);
  console.log(`categories=${categories.length}, answers=${answers.length}, questions=${questions.length}, nodes=${chainNodes.length}`);
}

main();
